### ISSUE TITLE
Translation efforts url in the readme returns a 404 page

### ISSUE THREAD

**Issue by neicore** [reactjs/sw.react.dev#2]
![image](https://user-images.githubusercontent.com/28825727/235288225-302ec046-3ca7-4b46-8421-95048392f070.png)

**Comment by orama254** [comment]
Hello, @neicore,  thanks for checking out the project. We will be looking at how to put an appropriate link there. Also feel free to make suggestions based on what other translation projects have done.

**Comment by orama254** [comment]
Also @neicore, do you know of other folks in Tz who use react and are willing to help with translation to Swahili?

**Comment by neicore** [comment]
Hello @orama254 

I have shared and will keep sharing this in my network to get people to contribute. I currently have my hands full will another project but will definitely contribute when I get a chance.

**Comment by Lynnmwova** [comment]
Hello @orama254 I'm Kenyan and very willing to help with the translation to Swahili. However, I'm still experiencing the same issue @neicore had with the translation efforts URL returning a 404 error. I'm open to your suggestions.

**Comment by orama254** [comment]
Hello @Lynnmwova,

The link should point to issue #1 . Feel free to make a pull request that fixes this and also let me know if you need any assistance with it.

cc @neicore

**Comment by Lynnmwova** [comment]
I will do exactly that. Thank you!

**Comment by orama254** [comment]
Closing this as resolved, feel free to contribute to the translation or to refer others as well to contribute.

cc @neicore @Lynnmwova
